apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deploy
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:           
      containers:
      - name: orderapi
        image: 47972/bookorderapi:latest        
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__SqlConnection
          value: "Data Source=mssql;Initial Catalog=OrderDB;Persist Security Info=True;User ID=sa;Password=Labuser@123456"
