apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deploy
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:           
      containers:
      - name: catalogapi
        image: 47972/catalogapi:latest        
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__SqlConnection
          value: "Data Source=mssql;Initial Catalog=CatalogDB;Persist Security Info=True;User ID=sa;Password=Labuser@123456"
